apiVersion: v1
kind: Service
metadata:
  namespace: qraft
  name: proxy-service
spec:
  selector:
    app: proxy
  ports:
    - protocol: TCP
      port: 25577
      targetPort: 25565
  type: LoadBalancer