apiVersion: v1
kind: Service
metadata:
  namespace: qraft
  name: minecraft-service
spec:
  selector:
    app: minecraft
  ports:
    - protocol: TCP
      port: 25565
      targetPort: 25565
  type: LoadBalancer